import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";

// The five moments worth counting, in the order a visit passes through them.
// The order is the funnel the back-office draws, so adding one means deciding
// where it sits — and adding it to the check constraint in migration 0008,
// which is what actually refuses anything else.
export const EVENT_NAMES = [
  "visit",
  "works_seen",
  "contact_seen",
  "form_opened",
  "cv_download",
] as const;
export type EventName = (typeof EVENT_NAMES)[number];

export const EVENT_LABELS: Record<EventName, string> = {
  visit: "Visits",
  works_seen: "Saw the work",
  contact_seen: "Scrolled to the end",
  form_opened: "Opened the form",
  cv_download: "Downloaded the CV",
};

export type EventCounts = Record<EventName, number>;
export type EventSummary = {
  last7: EventCounts;
  last30: EventCounts;
  // Null when the table isn't there yet — migration 0008 hasn't been run —
  // which the back-office says out loud rather than drawing a page of zeroes.
  since: string | null;
  ready: boolean;
};

type EventsTable = {
  from(table: "site_events"): {
    insert(rows: { name: string; visit: string }[]): PromiseLike<{
      error: { message: string; code?: string } | null;
    }>;
    select(columns: string): {
      gte(
        column: string,
        value: string,
      ): PromiseLike<{
        data: { name: string; created_at: string }[] | null;
        error: { message: string; code?: string } | null;
      }>;
    };
  };
};

async function eventsTable() {
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  return (supabaseAdmin as unknown as EventsTable).from("site_events");
}

function emptyCounts(): EventCounts {
  return Object.fromEntries(EVENT_NAMES.map((name) => [name, 0])) as EventCounts;
}

// Called by the page, so it is open to anyone who can open the page. That is
// the trade every analytics endpoint makes; what keeps it cheap is that the
// name is checked against a fixed list here and again by a check constraint in
// the database, and one visit can only ever write one row per name.
export const recordEvent = createServerFn({ method: "POST" })
  .validator(
    z.object({
      name: z.enum(EVENT_NAMES),
      // Generated by the browser per tab session; not a person, not stored
      // anywhere else, and never read back out except to count distinct ones.
      visit: z.string().regex(/^[a-z0-9-]{8,64}$/),
    }),
  )
  .handler(async ({ data }): Promise<{ ok: true }> => {
    try {
      // Eddie opening his own site shouldn't show up as interest in it. The
      // session cookie is httpOnly, so only the server can tell — which is
      // also why the page can't skip the call itself.
      const { requireAdmin } = await import("./admin-session");
      const isAdmin = await requireAdmin().then(
        () => true,
        () => false,
      );
      if (isAdmin) return { ok: true };

      const { error } = await (await eventsTable()).insert([{ name: data.name, visit: data.visit }]);
      // 23505 is the unique index doing its job: this visit has already been
      // counted for this name. Nothing to report.
      if (error && error.code !== "23505") throw new Error(error.message);
    } catch (cause) {
      // A page must never fail because a counter did.
      console.error("[events] Not recorded", cause);
    }
    return { ok: true };
  });

export const adminEventSummary = createServerFn({ method: "POST" }).handler(
  async (): Promise<EventSummary> => {
    const { requireAdmin } = await import("./admin-session");
    await requireAdmin();

    const since = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
    const { data, error } = await (await eventsTable())
      .select("name,created_at")
      .gte("created_at", since.toISOString());

    // 42P01 is "relation does not exist" — migration 0008 hasn't been run.
    // Lovable doesn't apply the files on push; someone has to paste it into
    // the SQL editor, and until they do this is the honest answer.
    if (error) {
      if (error.code === "42P01") {
        return { last7: emptyCounts(), last30: emptyCounts(), since: null, ready: false };
      }
      throw new Error(error.message);
    }

    const sevenDaysAgo = Date.now() - 7 * 24 * 60 * 60 * 1000;
    const last7 = emptyCounts();
    const last30 = emptyCounts();
    for (const row of data ?? []) {
      const name = row.name as EventName;
      if (!(name in last30)) continue;
      last30[name] += 1;
      if (new Date(row.created_at).getTime() >= sevenDaysAgo) last7[name] += 1;
    }

    return { last7, last30, since: since.toISOString(), ready: true };
  },
);
