import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";

// The five moments worth counting, in the order a visit passes through them.
// The order is the funnel the back-office draws, so adding one means deciding
// where it sits — and adding it to the check constraint in migration 0008,
// which is what actually refuses anything else.
export const EVENT_NAMES = [
  "visit",
  "works_seen",
  "contact_seen",
  "form_opened",
  "cv_download",
] as const;
export type EventName = (typeof EVENT_NAMES)[number];

export const EVENT_LABELS: Record<EventName, string> = {
  visit: "Visits",
  works_seen: "Saw the work",
  contact_seen: "Scrolled to the end",
  form_opened: "Opened the form",
  cv_download: "Downloaded the CV",
};

export type EventCounts = Record<EventName, number>;
export type Breakdown = { label: string; value: number }[];

export type EventWindow = {
  counts: EventCounts;
  source: Breakdown;
  device: Breakdown;
  country: Breakdown;
};

export type EventSummary = {
  last7: EventWindow;
  last30: EventWindow;
  // False when the table isn't there yet — migration 0008 hasn't been run —
  // which the back-office says out loud rather than drawing a page of zeroes.
  ready: boolean;
  // False when 0008 has run but 0009 hasn't: the funnel works, the three
  // breakdowns have nowhere to come from.
  hasContext: boolean;
};

type EventRow = {
  name: string;
  created_at: string;
  source?: string | null;
  device?: string | null;
  country?: string | null;
};

type EventsTable = {
  from(table: "site_events"): {
    insert(rows: Record<string, string | null>[]): PromiseLike<{
      error: { message: string; code?: string } | null;
    }>;
    select(columns: string): {
      gte(
        column: string,
        value: string,
      ): PromiseLike<{
        data: EventRow[] | null;
        error: { message: string; code?: string } | null;
      }>;
    };
  };
};

async function eventsTable() {
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  return (supabaseAdmin as unknown as EventsTable).from("site_events");
}

function emptyCounts(): EventCounts {
  return Object.fromEntries(EVENT_NAMES.map((name) => [name, 0])) as EventCounts;
}

// Three buckets, from the user agent and nothing else — the string itself is
// read and thrown away. iPad reports itself as a Macintosh in recent iOS, so
// the touch hint is what separates it from a laptop.
function deviceFrom(agent: string): "mobile" | "tablet" | "desktop" {
  const ua = agent.toLowerCase();
  if (/ipad|tablet|playbook|silk|(android(?!.*mobile))/.test(ua)) return "tablet";
  if (/macintosh/.test(ua) && /mobile|touch/.test(ua)) return "tablet";
  if (/mobi|iphone|ipod|android|blackberry|iemobile|opera mini/.test(ua)) return "mobile";
  return "desktop";
}

// A hostname, never a path: "linkedin.com" is worth knowing, which post
// someone clicked from isn't ours to keep. Facebook and Instagram each arrive
// under several hostnames; they're the same answer to "where from".
function tidySource(host: string): string {
  const clean = host.replace(/^www\./, "").toLowerCase();
  if (!clean) return "Direct";
  if (/(^|\.)facebook\.com$|^l\.facebook|^lm\.facebook|^m\.facebook/.test(clean)) return "facebook.com";
  if (/(^|\.)instagram\.com$|^l\.instagram/.test(clean)) return "instagram.com";
  if (/(^|\.)linkedin\.com$|^lnkd\.in$/.test(clean)) return "linkedin.com";
  if (/(^|\.)google\./.test(clean)) return "google";
  return clean;
}

// Called by the page, so it is open to anyone who can open the page. That is
// the trade every analytics endpoint makes; what keeps it cheap is that the
// name is checked against a fixed list here and again by a check constraint in
// the database, and one visit can only ever write one row per name.
export const recordEvent = createServerFn({ method: "POST" })
  .validator(
    z.object({
      name: z.enum(EVENT_NAMES),
      // Generated by the browser per tab session; not a person, not stored
      // anywhere else, and never read back out except to count distinct ones.
      visit: z.string().regex(/^[a-z0-9-]{8,64}$/),
      // document.referrer's hostname, sent by the page because the request the
      // page makes carries its own address as the referer, not the one the
      // visitor arrived from. Empty means they typed it, or came from a link
      // that sends no referrer at all.
      ref: z.string().max(120).optional(),
    }),
  )
  .handler(async ({ data }): Promise<{ ok: true }> => {
    try {
      // Eddie opening his own site shouldn't show up as interest in it. The
      // session cookie is httpOnly, so only the server can tell — which is
      // also why the page can't skip the call itself.
      const { requireAdmin } = await import("./admin-session");
      const isAdmin = await requireAdmin().then(
        () => true,
        () => false,
      );
      if (isAdmin) return { ok: true };

      const row: Record<string, string | null> = { name: data.name, visit: data.visit };

      // Only the visit row carries the context. The other four are the same
      // visit, so repeating it would be four copies of one fact.
      if (data.name === "visit") {
        const { getRequestHeader } = await import("@tanstack/react-start/server");
        const agent = getRequestHeader("user-agent") ?? "";
        const country = (getRequestHeader("cf-ipcountry") ?? "").toUpperCase();

        row["source"] = tidySource(data.ref ?? "");
        row["device"] = deviceFrom(agent);
        row["country"] = /^[A-Z]{2}$/.test(country) && country !== "XX" && country !== "T1"
          ? country
          : null;
      }

      const { error } = await (await eventsTable()).insert([row]);
      // 23505 is the unique index doing its job: this visit has already been
      // counted for this name. Nothing to report.
      if (error && error.code !== "23505") throw new Error(error.message);
    } catch (cause) {
      // A page must never fail because a counter did.
      console.error("[events] Not recorded", cause);
    }
    return { ok: true };
  });

function tally(rows: EventRow[], field: "source" | "device" | "country"): Breakdown {
  const counts = new Map<string, number>();
  for (const row of rows) {
    const value = row[field];
    if (!value) continue;
    counts.set(value, (counts.get(value) ?? 0) + 1);
  }
  return [...counts.entries()]
    .map(([label, value]) => ({ label, value }))
    .sort((a, b) => b.value - a.value);
}

function summarise(rows: EventRow[]): EventWindow {
  const counts = emptyCounts();
  for (const row of rows) {
    const name = row.name as EventName;
    if (name in counts) counts[name] += 1;
  }
  const visits = rows.filter((row) => row.name === "visit");
  return {
    counts,
    source: tally(visits, "source"),
    device: tally(visits, "device"),
    country: tally(visits, "country"),
  };
}

export const adminEventSummary = createServerFn({ method: "POST" }).handler(
  async (): Promise<EventSummary> => {
    const { requireAdmin } = await import("./admin-session");
    await requireAdmin();

    const since = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
    // "*" rather than a column list so this still works either side of
    // migration 0009: before it, the three context columns simply aren't in
    // the rows, and hasContext says so instead of the query failing.
    const { data, error } = await (await eventsTable())
      .select("*")
      .gte("created_at", since.toISOString());

    // 42P01 is "relation does not exist" — migration 0008 hasn't been run.
    // Lovable doesn't apply the files on push; someone has to paste it into
    // the SQL editor, and until they do this is the honest answer.
    if (error) {
      if (error.code === "42P01") {
        const empty = summarise([]);
        return { last7: empty, last30: empty, ready: false, hasContext: false };
      }
      throw new Error(error.message);
    }

    const rows = data ?? [];
    const sevenDaysAgo = Date.now() - 7 * 24 * 60 * 60 * 1000;
    const recent = rows.filter((row) => new Date(row.created_at).getTime() >= sevenDaysAgo);

    return {
      last7: summarise(recent),
      last30: summarise(rows),
      ready: true,
      hasContext: rows.length === 0 || "source" in rows[0]!,
    };
  },
);
